// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="About Oyerweb"
          descriptions={[
            "We specialize in crafting professional websites that don't just look good but perform exceptionally. Our goal is to drive real, measurable traction to your business.",
            "With Oyerweb, you get a partner who understands the digital landscape and knows exactly what it takes to convert visitors into loyal customers.",
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
