// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Ready to Grow?"
          text="Get in touch with Oyerweb today to start your digital transformation."
          primaryButton={{
            text: "Call 727-221-2651",
            href: "tel:727-221-2651",
          }}
          secondaryButton={{
            text: "Email Us",
            href: "mailto:stevenoyer6@gmail.com",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
