// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="FAQs"
          title="Frequently Asked Questions"
          description="Have questions? We have answers."
          items={[
            {
              question: "How long does a site take?",
              answer: "Typical turnarounds are 2-4 weeks depending on complexity.",
            },
            {
              question: "Do you guarantee results?",
              answer: "Yes, we focus on conversion-driven design to ensure your traffic grows.",
            },
            {
              question: "Can I update content later?",
              answer: "We provide a user-friendly dashboard for easy self-updates.",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
