// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesDetailedCards from '@/components/sections/features/FeaturesDetailedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesDetailedCards
          tag="Our Services"
          title="What We Deliver"
          description="Powerful features to scale your digital presence."
          items={[
            {
              title: "SEO Optimization",
              description: "Higher rankings ensure your customers find you first.",
              tags: [
                "SEO",
                "Growth",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/line-graph-data-analysis-icon_53876-20802.jpg",
            },
            {
              title: "Mobile First Design",
              description: "Flawless user experience on every device.",
              tags: [
                "Responsive",
                "Mobile",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/birth-rate-fertility-concept_23-2148760992.jpg",
            },
            {
              title: "Conversion Rate Optimization",
              description: "Turn more clicks into qualified leads.",
              tags: [
                "Sales",
                "Growth",
              ],
              imageSrc: "http://img.b2bpic.net/free-vector/laptop-with-rocket-start-up_24908-80976.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
