// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Our Impact"
          title="Driving Results Daily"
          description="We don't guess, we deliver."
          metrics={[
            {
              value: "100+",
              description: "Websites Built",
            },
            {
              value: "200%",
              description: "Avg. Traffic Growth",
            },
            {
              value: "24/7",
              description: "Support Ready",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
