// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingSimpleCards from '@/components/sections/pricing/PricingSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingSimpleCards
          tag="Our Plans"
          title="Straightforward Pricing"
          description="Scalable web solutions tailored to your business needs."
          plans={[
            {
              tag: "Basic",
              price: "$999",
              description: "Standard business site",
              features: [
                "Mobile Responsive",
                "SEO Optimized",
                "Fast Support",
              ],
            },
            {
              tag: "Pro",
              price: "$1,999",
              description: "Custom conversion machine",
              features: [
                "Everything in Basic",
                "Advanced Analytics",
                "Lead Gen Forms",
              ],
            },
            {
              tag: "Enterprise",
              price: "Custom",
              description: "Full growth platform",
              features: [
                "E-commerce",
                "CRM Integration",
                "Priority 24/7 Support",
              ],
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
