// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
          tag="Social Proof"
          title="Clients Who Grew With Us"
          testimonials={[
            {
              name: "Sarah J.",
              role: "Owner",
              company: "LocalCafe",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/business-woman-green-suit-using-phone-outside-street_1303-29546.jpg",
            },
            {
              name: "Michael B.",
              role: "CEO",
              company: "TechStartup",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/young-successful-businessman-smiling-posing-with-crossed-arms-office_176420-910.jpg",
            },
            {
              name: "Linda M.",
              role: "Manager",
              company: "BoutiqueShop",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-illustrator-drawing-tablet_23-2150040139.jpg",
            },
            {
              name: "David K.",
              role: "Director",
              company: "LawFirm",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/blond-businessman-happy-expression_1194-3796.jpg",
            },
            {
              name: "Rachel P.",
              role: "Founder",
              company: "CreativeStudio",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/business-owner-working-their-strategy_23-2149241320.jpg",
            },
          ]}
          description="Trusted by businesses to deliver real results."
        />
        </SectionErrorBoundary>
      </div>
  );
}
